projects:
  backend:
    schemaPath: generated/prisma.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: generated/prisma.ts
        generator: prisma-ts
